準備

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

等差数列

In [3]:
# NumPy等差数列の記法1，(start=初項, stop=末項（注意：その数を含まない）, step=等差)
a1 = np.arange(start=1, stop=11, step=2)
a1

array([1, 3, 5, 7, 9])

In [4]:
# NumPy等差数列の記法2，(start=初項, stop=末項, num=項数)
a2 = np.linspace(start=1, stop=9, num=5)
a2

array([1., 3., 5., 7., 9.])

等比数列

In [5]:
# NumPy等比数列の記法1，(start=base^初項，stop=base^末項，num=項数，base=底)
a3 = np.logspace(start=1, stop=4, num=4, base=2)
a3

array([ 2.,  4.,  8., 16.])

In [6]:
# NumPy等比数列の記法2，(start=初項，stop=末項，num=項数)
a4 = np.geomspace(start=1, stop=16, num=5)
a4

array([ 1.,  2.,  4.,  8., 16.])

数列和

In [7]:
# NumPyで数列和
s1 = np.sum(a1)
s1

25

漸化式

In [8]:
# NumPyで等差数列の漸化式
Seq1 = np.zeros(5)
Seq1[0] = 1  # 初項

for N in range(1, 5):
    Seq1[N] = Seq1[N-1] + 2  # 式を書く

Seq1

array([1., 3., 5., 7., 9.])

In [9]:
# NumPyで等比数列の漸化式
Seq2 = np.zeros(5)
Seq2[0] = 1  # 初項

for N in range(1, 5):
    Seq2[N] = Seq2[N-1] * 2  # 式を書く

Seq2

array([ 1.,  2.,  4.,  8., 16.])